name: Run Norminette, Tests and deploy coverage report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image from GHCR
        run: docker pull ghcr.io/t-pereira06/ubuntu-docker:latest

      - name: Run Norminette inside Container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app/libft ghcr.io/t-pereira06/ubuntu-docker:latest norminette /app/libft || exit 1

      - name: Compile application
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/t-pereira06/ubuntu-docker:latest \
            bash -c "make" || exit 1

      - name: Run Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/t-pereira06/ubuntu-docker:latest \
            bash -c "./tests/bin/run_tests" || exit 1

      - name: Run Tests and Upload Coverage to Codecov
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} \
            ghcr.io/t-pereira06/ubuntu-docker:latest \
            bash -c "make coverage"

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.info
          slug: t-pereira06/42_libft
          fail_ci_if_error: true

      - name: Upload coverage-report to GitHub Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: coverage-report

  deploy:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
