name: Run Norminette Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image from GHCR
        run: docker pull ghcr.io/t-pereira06/ubuntu-docker:latest

      - name: Run Norminette inside Container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app/libft ghcr.io/t-pereira06/ubuntu-docker:latest norminette /app/libft || exit 1

      - name: Compile application
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/t-pereira06/ubuntu-docker:latest \
            bash -c "make" || exit 1

      - name: Run Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/t-pereira06/ubuntu-docker:latest \
            bash -c "./tests/bin/run_tests" || exit 1

      - name: Run Tests and Upload Coverage to Codecov
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} \
            ghcr.io/t-pereira06/ubuntu-docker:latest \
            bash -c "
              make coverage &&
              curl -Os https://uploader.codecov.io/latest/linux/codecov &&
              chmod +x codecov &&
              ./codecov -t \$CODECOV_TOKEN
            "
