name: Run Norminette Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image from GHCR
        run: docker pull ghcr.io/t-pereira06/ubuntu-norminette:latest

  norminette:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run Norminette inside Container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app/libft ghcr.io/t-pereira06/ubuntu-norminette:latest norminette /app/libft || exit 1

  tests:
    needs: norminette
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile application
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/t-pereira06/ubuntu-gtest:latest \
            bash -c "make" || exit 1

      - name: Run Tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/t-pereira06/ubuntu-gtest:latest \
            bash -c "./run_tests" || exit 1
